version: '3.8'

services:
  enabl-webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.local
    restart: unless-stopped
    networks:
      - enabl-network

networks:
  enabl-network:
    driver: bridge
