#!/bin/bash

# Manual Staging Environment Configuration
# This script provides instructions for configuring staging after App Runner service creation

echo "🚀 Enabl Health Staging Environment Configuration"
echo "================================================"
echo ""

echo "✅ App Runner service 'enabl-health-staging' already exists"
echo ""

echo "📝 STEP 1: Configure Environment Variables in AWS Console"
echo "--------------------------------------------------------"
echo "Go to: https://console.aws.amazon.com/apprunner/home?region=us-east-1#/services"
echo "1. Click on 'enabl-health-staging' service"
echo "2. Go to Configuration > Environment variables"
echo "3. Add these environment variables:"
echo ""
echo "NEXT_PUBLIC_API_URL=https://y1rp7krhca.execute-api.us-east-1.amazonaws.com/staging/"
echo "NEXT_PUBLIC_AI_API_URL=https://rs9kwccdr9.execute-api.us-east-1.amazonaws.com/prod/"
echo "NEXT_PUBLIC_COGNITO_USER_POOL_ID=us-east-1_ex9P9pFRA"
echo "NEXT_PUBLIC_COGNITO_USER_POOL_CLIENT_ID=2stjv7o8orrnp9r1sno1k8kgan"
echo "NEXT_PUBLIC_COGNITO_DOMAIN=enabl-auth-staging"
echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=665236506157-j0kr2dhcms8cvgjcoa27k11mejqn59qf.apps.googleusercontent.com"
echo "NODE_ENV=production"
echo "NEXT_PUBLIC_APP_ENV=staging"
echo ""
echo "4. Click 'Save' and wait for deployment to complete"
echo ""

echo "🌐 STEP 2: Configure Custom Domain"
echo "-----------------------------------"
echo "1. In the same service console, go to Configuration > Custom domains"
echo "2. Click 'Link domain'"
echo "3. Enter domain: staging.enabl.health"
echo "4. Note the CNAME target that appears (something like: randomstring.us-east-1.awsapprunner.com)"
echo ""

echo "🔗 STEP 3: Configure DNS in Route53"
echo "------------------------------------"
echo "Run this command with the CNAME target from Step 2:"
echo ""
echo "aws route53 change-resource-record-sets --hosted-zone-id Z01234567890ABCDEFGHI --change-batch '"
echo "{"
echo "  \"Changes\": [{"
echo "    \"Action\": \"UPSERT\","
echo "    \"ResourceRecordSet\": {"
echo "      \"Name\": \"staging.enabl.health\","
echo "      \"Type\": \"CNAME\","
echo "      \"TTL\": 300,"
echo "      \"ResourceRecords\": [{\"Value\": \"YOUR_CNAME_TARGET_FROM_STEP_2\"}]"
echo "    }"
echo "  }]"
echo "}'"
echo ""

echo "✅ STEP 4: Test the Staging Environment"
echo "---------------------------------------"
echo "After DNS propagation (5-10 minutes), test:"
echo "curl -I https://staging.enabl.health"
echo ""

echo "🎉 Staging environment will be accessible at: https://staging.enabl.health"
echo ""
echo "📋 Next: Once staging is working, run production setup:"
echo "./scripts/setup-production.sh"
